import React, { useState } from 'react';
import { Box, CssBaseline, List, ListItem, ListItemAvatar, ListItemText, Avatar, useTheme } from '@mui/material';

import { SignIn } from './features/sign-in/SignIn';
import { SignUp } from './features/sign-up/SignUp';
import { Dashboard } from './features/dashboard/Dashboard';

import { MiniDrawer } from './components/drawers/MiniDrawer';
import { TopNavBar } from './components/navbars/topNav/TopNavBar';
import { BottomNavBar } from './components/navbars/bottomNav/BottomNavbar';

const refreshMessages = () => {
	const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

	return Array.from(new Array(50)).map(
		() => messageExamples[getRandomInt(messageExamples.length)],
	);
};

export const App = () => {
	const theme = useTheme();
	const [bottom, setBottom] = useState(0);
	const [messages, setMessages] = useState(refreshMessages())
	
	return (
		<Box>
			<CssBaseline />
			<TopNavBar/>
			
			<Box 
				sx={{
					display: 'flex',
					pb:7, 
					pt:'117px',
					[theme.breakpoints.up('sm')]: {
						pt: '125px', // Height for screens defined in the 'sm' breakpoint and up (desktop)
					}
				}}
			>
				<MiniDrawer/>
				
				<List>
					{ messages.map( ( { primary, secondary, person }, index) => (
						<ListItem button key={index + person}>
							<ListItemAvatar>
								<Avatar alt="Profile Picture" src={person} />
							</ListItemAvatar>
							<ListItemText primary={primary} secondary={secondary} />
						</ListItem>
					) ) }
				</List>
		\
			</Box>
			<BottomNavBar className='footerNav' bottom={bottom} setBottom={setBottom}/>
		</Box>
	);
};

const messageExamples = [
	{
	  primary: 'Brunch this week?',
	  secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
	  person: '/static/images/avatar/5.jpg',
	},
	{
	  primary: 'Birthday Gift',
	  secondary: `Do you have a suggestion for a good present for John on his work
	    anniversary. I am really confused & would love your thoughts on it.`,
	  person: '/static/images/avatar/1.jpg',
	},
	{
	  primary: 'Recipe to try',
	  secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
	  person: '/static/images/avatar/2.jpg',
	},
	{
	  primary: 'Yes!',
	  secondary: 'I have the tickets to the ReactConf for this year.',
	  person: '/static/images/avatar/3.jpg',
	},
	{
	  primary: "Doctor's Appointment",
	  secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
	  person: '/static/images/avatar/4.jpg',
	},
	{
	  primary: 'Discussion',
	  secondary: `Menus that are generated by the bottom app bar (such as a bottom
	    navigation drawer or overflow menu) open as bottom sheets at a higher elevation
	    than the bar.`,
	  person: '/static/images/avatar/5.jpg',
	},
	{
	  primary: 'Summer BBQ',
	  secondary: `Who wants to have a cookout this weekend? I just got some furniture
	    for my backyard and would love to fire up the grill.`,
	  person: '/static/images/avatar/1.jpg',
	},
];